import type {
  Agent,
  AppNotification,
  Campaign,
  Company,
  Contact,
  Conversation,
  EmailDraft,
  LogEntry,
  Meeting,
} from "./types";

export const TONES = [
  { label: "Professional", value: "professional" },
  { label: "Friendly", value: "friendly" },
  { label: "Concise & Direct", value: "concise" },
  { label: "Consultative", value: "consultative" },
  { label: "Enthusiastic", value: "enthusiastic" },
];

export const campaigns: Campaign[] = [
  {
    id: "cmp_apex",
    name: "Apex Cloud — Q2 Enterprise Push",
    product: "Apex Cloud Data Platform",
    status: "Running",
    createdAt: "2026-05-04",
    companiesUploaded: 480,
    companiesResearched: 480,
    emailsSent: 162,
    repliesReceived: 34,
    meetingsBooked: 9,
    topN: 50,
    tone: "consultative",
  },
  {
    id: "cmp_fintech",
    name: "FinTech Mid-Market Expansion",
    product: "LedgerOne Payments API",
    status: "Running",
    createdAt: "2026-05-12",
    companiesUploaded: 220,
    companiesResearched: 198,
    emailsSent: 71,
    repliesReceived: 12,
    meetingsBooked: 3,
    topN: 40,
    tone: "professional",
  },
  {
    id: "cmp_health",
    name: "HealthOps Pilot Outreach",
    product: "HealthOps Scheduling Suite",
    status: "Paused",
    createdAt: "2026-04-21",
    companiesUploaded: 130,
    companiesResearched: 130,
    emailsSent: 88,
    repliesReceived: 21,
    meetingsBooked: 6,
    topN: 30,
    tone: "friendly",
  },
  {
    id: "cmp_retail",
    name: "Retail Analytics — Spring",
    product: "ShelfIQ Analytics",
    status: "Completed",
    createdAt: "2026-03-02",
    companiesUploaded: 310,
    companiesResearched: 310,
    emailsSent: 240,
    repliesReceived: 58,
    meetingsBooked: 17,
    topN: 60,
    tone: "concise",
  },
  {
    id: "cmp_logi",
    name: "Logistics Net-New (Draft)",
    product: "CargoX Route Optimizer",
    status: "Draft",
    createdAt: "2026-05-25",
    companiesUploaded: 0,
    companiesResearched: 0,
    emailsSent: 0,
    repliesReceived: 0,
    meetingsBooked: 0,
    topN: 50,
    tone: "professional",
  },
];

export const companies: Company[] = [
  {
    id: "co_northwind",
    campaignId: "cmp_apex",
    name: "Northwind Logistics",
    domain: "northwind.com",
    industry: "Logistics & Supply Chain",
    size: "1,000–5,000",
    location: "Chicago, US",
    aiScore: 94,
    rank: 1,
    matchLevel: "Strong",
    status: "Approved",
    researchSummary:
      "Mid-large 3PL operator modernizing its data stack. Recently migrated core ops to cloud and is consolidating analytics vendors — strong fit for a unified data platform.",
    matchExplanation:
      "High product fit (cloud migration in progress), strong industry alignment, and active hiring for data engineering roles signal budget and intent.",
    scoreFactors: [
      { label: "Product fit", weight: 0.3, score: 96 },
      { label: "Industry alignment", weight: 0.2, score: 92 },
      { label: "Company relevance", weight: 0.15, score: 90 },
      { label: "Requirement satisfaction", weight: 0.15, score: 95 },
      { label: "Market compatibility", weight: 0.1, score: 88 },
      { label: "Growth indicators", weight: 0.1, score: 99 },
    ],
    recentFunding: "Series D — $120M (Feb 2026)",
    recentNews: undefined,
    activeHiring: true,
    contactsFound: 3,
    contactsVerified: 2,
  },
  {
    id: "co_brightwave",
    campaignId: "cmp_apex",
    name: "Brightwave Manufacturing",
    domain: "brightwave.io",
    industry: "Industrial Manufacturing",
    size: "500–1,000",
    location: "Austin, US",
    aiScore: 88,
    rank: 2,
    matchLevel: "Strong",
    status: "Approved",
    researchSummary:
      "Smart-factory manufacturer generating large telemetry volumes. Public statements emphasize data-driven operations and predictive maintenance initiatives.",
    matchExplanation:
      "Strong requirement satisfaction around real-time analytics; growth indicators solid. Slightly lower industry alignment than logistics ICP.",
    scoreFactors: [
      { label: "Product fit", weight: 0.3, score: 90 },
      { label: "Industry alignment", weight: 0.2, score: 82 },
      { label: "Company relevance", weight: 0.15, score: 88 },
      { label: "Requirement satisfaction", weight: 0.15, score: 91 },
      { label: "Market compatibility", weight: 0.1, score: 85 },
      { label: "Growth indicators", weight: 0.1, score: 90 },
    ],
    activeHiring: true,
    contactsFound: 3,
    contactsVerified: 3,
  },
  {
    id: "co_summit",
    campaignId: "cmp_apex",
    name: "Summit Retail Group",
    domain: "summitretail.com",
    industry: "Retail",
    size: "5,000+",
    location: "Seattle, US",
    aiScore: 79,
    rank: 3,
    matchLevel: "Good",
    status: "Qualified",
    researchSummary:
      "National retail chain with a maturing analytics team. Recent press notes a cost-optimization program that may slow new vendor spend this quarter.",
    matchExplanation:
      "Good product fit but recent cost-cutting news lowers timing score. Large org increases relevance but lengthens sales cycle.",
    scoreFactors: [
      { label: "Product fit", weight: 0.3, score: 84 },
      { label: "Industry alignment", weight: 0.2, score: 76 },
      { label: "Company relevance", weight: 0.15, score: 88 },
      { label: "Requirement satisfaction", weight: 0.15, score: 74 },
      { label: "Market compatibility", weight: 0.1, score: 72 },
      { label: "Growth indicators", weight: 0.1, score: 60 },
    ],
    recentNews: "Announced 5% cost-reduction program (Apr 2026)",
    activeHiring: false,
    contactsFound: 2,
    contactsVerified: 1,
  },
  {
    id: "co_vertex",
    campaignId: "cmp_apex",
    name: "Vertex Health Systems",
    domain: "vertexhealth.org",
    industry: "Healthcare",
    size: "1,000–5,000",
    location: "Boston, US",
    aiScore: 71,
    rank: 4,
    matchLevel: "Good",
    status: "Researching",
    researchSummary:
      "Regional hospital network with strict compliance requirements. Data residency and HIPAA constraints add procurement complexity.",
    matchExplanation:
      "Moderate fit; compliance overhead reduces requirement satisfaction. Stable but slow-moving buyer.",
    scoreFactors: [
      { label: "Product fit", weight: 0.3, score: 72 },
      { label: "Industry alignment", weight: 0.2, score: 68 },
      { label: "Company relevance", weight: 0.15, score: 80 },
      { label: "Requirement satisfaction", weight: 0.15, score: 64 },
      { label: "Market compatibility", weight: 0.1, score: 70 },
      { label: "Growth indicators", weight: 0.1, score: 66 },
    ],
    activeHiring: true,
    contactsFound: 1,
    contactsVerified: 0,
  },
  {
    id: "co_orbit",
    campaignId: "cmp_apex",
    name: "Orbit Media Holdings",
    domain: "orbitmedia.tv",
    industry: "Media & Entertainment",
    size: "200–500",
    location: "Los Angeles, US",
    aiScore: 52,
    rank: 5,
    matchLevel: "Weak",
    status: "Excluded",
    researchSummary:
      "Smaller media holding company with limited public signals of a data modernization initiative.",
    matchExplanation:
      "Low requirement satisfaction and weak growth indicators. Excluded by reviewer — outside core ICP.",
    scoreFactors: [
      { label: "Product fit", weight: 0.3, score: 50 },
      { label: "Industry alignment", weight: 0.2, score: 48 },
      { label: "Company relevance", weight: 0.15, score: 55 },
      { label: "Requirement satisfaction", weight: 0.15, score: 46 },
      { label: "Market compatibility", weight: 0.1, score: 58 },
      { label: "Growth indicators", weight: 0.1, score: 52 },
    ],
    recentNews: "Reported flat YoY revenue (Q1 2026)",
    activeHiring: false,
    contactsFound: 0,
    contactsVerified: 0,
  },
];

export const contacts: Contact[] = [
  {
    id: "ct_1",
    companyId: "co_northwind",
    companyName: "Northwind Logistics",
    name: "Dana Whitfield",
    role: "VP of Data & Analytics",
    email: "dana.whitfield@northwind.com",
    linkedin: "linkedin.com/in/danawhitfield",
    verification: "Verified",
    confidence: 96,
    approved: true,
  },
  {
    id: "ct_2",
    companyId: "co_northwind",
    companyName: "Northwind Logistics",
    name: "Marcus Lee",
    role: "Director of Engineering",
    email: "m.lee@northwind.com",
    linkedin: "linkedin.com/in/marcuslee",
    verification: "Verified",
    confidence: 91,
    approved: true,
  },
  {
    id: "ct_3",
    companyId: "co_northwind",
    companyName: "Northwind Logistics",
    name: "Priya Nair",
    role: "Head of Operations",
    email: "priya.nair@northwind.com",
    verification: "Risky",
    confidence: 64,
    approved: null,
  },
  {
    id: "ct_4",
    companyId: "co_brightwave",
    companyName: "Brightwave Manufacturing",
    name: "Tom Schaefer",
    role: "CTO",
    email: "tom@brightwave.io",
    linkedin: "linkedin.com/in/tomschaefer",
    verification: "Verified",
    confidence: 93,
    approved: null,
  },
  {
    id: "ct_5",
    companyId: "co_brightwave",
    companyName: "Brightwave Manufacturing",
    name: "Elena Cortez",
    role: "VP Operations",
    email: "e.cortez@brightwave.io",
    verification: "Verified",
    confidence: 89,
    approved: null,
  },
  {
    id: "ct_6",
    companyId: "co_summit",
    companyName: "Summit Retail Group",
    name: "Greg Hollis",
    role: "Director of Analytics",
    email: "greg.hollis@summitretail.com",
    verification: "Unknown",
    confidence: 41,
    approved: null,
  },
];

export const emailDrafts: EmailDraft[] = [
  {
    id: "em_1",
    contactId: "ct_1",
    contactName: "Dana Whitfield",
    companyName: "Northwind Logistics",
    role: "VP of Data & Analytics",
    subject: "Unifying Northwind's analytics stack after the cloud migration",
    body: `Hi Dana,

Congratulations on Northwind's recent cloud migration — consolidating ops data is no small feat. As you bring analytics vendors together, teams in 3PL often hit a wall stitching telemetry, billing, and route data into one trustworthy source.

Apex Cloud gives data teams a single platform to model that data and serve it to ops in real time — most customers cut reporting lead time by 60% in the first quarter.

Would a 20-minute walkthrough next week be useful? I can tailor it to Northwind's route + warehouse data.`,
    footer: "Best,\nJordan Pierce\nAccount Executive, Apex Cloud\njordan@apexcloud.com · +1 (415) 555-0142",
    state: "Sent",
  },
  {
    id: "em_2",
    contactId: "ct_4",
    contactName: "Tom Schaefer",
    companyName: "Brightwave Manufacturing",
    role: "CTO",
    subject: "Predictive maintenance telemetry — one platform for Brightwave",
    body: `Hi Tom,

Your smart-factory push generates exactly the kind of high-volume telemetry that's painful to operationalize. Most manufacturers end up with data scattered across point tools.

Apex Cloud unifies that telemetry so your predictive-maintenance models get fresh, reliable inputs without a custom pipeline.

Open to a short technical demo this week?`,
    footer: "Best,\nJordan Pierce\nAccount Executive, Apex Cloud\njordan@apexcloud.com · +1 (415) 555-0142",
    state: "Queued",
  },
];

export const conversations: Conversation[] = [
  {
    id: "cv_1",
    campaignId: "cmp_apex",
    companyName: "Northwind Logistics",
    contactName: "Dana Whitfield",
    role: "VP of Data & Analytics",
    email: "dana.whitfield@northwind.com",
    lastActivity: "2026-05-27T09:12:00",
    unread: true,
    stage: "Replied",
    messages: [
      {
        id: "m1",
        from: "us",
        author: "Jordan Pierce",
        at: "2026-05-22T10:00:00",
        subject: "Unifying Northwind's analytics stack after the cloud migration",
        body: "Hi Dana, congratulations on Northwind's recent cloud migration... Would a 20-minute walkthrough next week be useful?",
      },
      {
        id: "m2",
        from: "them",
        author: "Dana Whitfield",
        at: "2026-05-27T09:12:00",
        body: "Hi Jordan — timely. We're actively evaluating platforms this quarter. Can you send availability for Thursday or Friday?",
      },
    ],
    aiSuggestion:
      "Dana is asking for availability. Suggest Thursday 2pm or Friday 11am ET, attach a 1-pager on 3PL data unification, and offer to include their data engineering lead (Marcus Lee).",
  },
  {
    id: "cv_2",
    campaignId: "cmp_apex",
    companyName: "Brightwave Manufacturing",
    contactName: "Tom Schaefer",
    role: "CTO",
    email: "tom@brightwave.io",
    lastActivity: "2026-05-26T16:40:00",
    unread: false,
    stage: "Contacted",
    messages: [
      {
        id: "m1",
        from: "us",
        author: "Jordan Pierce",
        at: "2026-05-26T16:40:00",
        subject: "Predictive maintenance telemetry — one platform for Brightwave",
        body: "Hi Tom, your smart-factory push generates exactly the kind of high-volume telemetry... Open to a short technical demo this week?",
      },
    ],
    aiSuggestion:
      "No reply after 1 day. A gentle follow-up is scheduled in 2 days referencing a relevant manufacturing case study.",
  },
  {
    id: "cv_3",
    campaignId: "cmp_health",
    companyName: "Cedar Clinics",
    contactName: "Dr. Amelia Ross",
    role: "Chief Medical Officer",
    email: "a.ross@cedarclinics.org",
    lastActivity: "2026-05-25T11:05:00",
    unread: false,
    stage: "Meeting",
    messages: [
      {
        id: "m1",
        from: "us",
        author: "Sam Ortega",
        at: "2026-05-20T09:00:00",
        subject: "Cutting scheduling no-shows at Cedar Clinics",
        body: "Hi Dr. Ross, no-shows are a quiet drain on clinic capacity...",
      },
      {
        id: "m2",
        from: "them",
        author: "Dr. Amelia Ross",
        at: "2026-05-24T14:20:00",
        body: "This is relevant. Let's set up a call.",
      },
      {
        id: "m3",
        from: "us",
        author: "Sam Ortega",
        at: "2026-05-25T11:05:00",
        body: "Wonderful — booked for May 29, 3:00pm. Calendar invite + Meet link sent.",
        isFollowUp: true,
      },
    ],
  },
];

export const meetings: Meeting[] = [
  {
    id: "mt_1",
    company: "Cedar Clinics",
    contact: "Dr. Amelia Ross",
    date: "2026-05-29",
    time: "3:00 PM ET",
    status: "Upcoming",
    link: "https://meet.example.com/cedar-apex",
    notes: "Focus on scheduling no-show reduction. Bring ROI calculator.",
  },
  {
    id: "mt_2",
    company: "Northwind Logistics",
    contact: "Dana Whitfield",
    date: "2026-05-30",
    time: "2:00 PM CT",
    status: "Upcoming",
    link: "https://meet.example.com/northwind-apex",
    notes: "Tailor to route + warehouse data. Invite Marcus Lee.",
  },
  {
    id: "mt_3",
    company: "Summit Retail Group",
    contact: "Greg Hollis",
    date: "2026-05-19",
    time: "10:30 AM PT",
    status: "Completed",
    link: "https://meet.example.com/summit-shelfiq",
    notes: "Interested but budget frozen until Q3. Follow up in July.",
  },
  {
    id: "mt_4",
    company: "Brightwave Manufacturing",
    contact: "Elena Cortez",
    date: "2026-05-15",
    time: "1:00 PM CT",
    status: "No-show",
    link: "https://meet.example.com/brightwave-apex",
  },
];

export const notifications: AppNotification[] = [
  {
    id: "nt_1",
    type: "reply",
    title: "New reply from Dana Whitfield",
    detail: "Northwind Logistics — asking for meeting availability.",
    at: "2026-05-27T09:12:00",
    read: false,
  },
  {
    id: "nt_2",
    type: "meeting",
    title: "Meeting scheduled",
    detail: "Cedar Clinics — May 29, 3:00 PM ET.",
    at: "2026-05-25T11:06:00",
    read: false,
  },
  {
    id: "nt_3",
    type: "followup",
    title: "Follow-up sent automatically",
    detail: "Brightwave Manufacturing — Tom Schaefer (no reply after 24h).",
    at: "2026-05-26T16:41:00",
    read: true,
  },
  {
    id: "nt_4",
    type: "verification",
    title: "Email verification failed",
    detail: "Greg Hollis (Summit Retail) returned status: Unknown.",
    at: "2026-05-24T08:30:00",
    read: true,
  },
  {
    id: "nt_5",
    type: "campaign",
    title: "Campaign completed",
    detail: "Retail Analytics — Spring finished with 17 meetings booked.",
    at: "2026-05-20T18:00:00",
    read: true,
  },
];

export const agents: Agent[] = [
  {
    id: "ag_enrich",
    name: "Company Enrichment",
    description:
      "Researches each uploaded company: profile, industry, size, funding, news, hiring signals.",
    enabled: true,
    order: 1,
    status: "Idle",
    lastRun: "2026-05-27T07:00:00",
  },
  {
    id: "ag_score",
    name: "Company Scoring",
    description:
      "Applies weighted scoring against your ICP and ranks companies with explainable factors.",
    enabled: true,
    order: 2,
    status: "Idle",
    lastRun: "2026-05-27T07:05:00",
  },
  {
    id: "ag_finder",
    name: "Employee Finder",
    description: "Identifies top decision-makers and relevant business contacts per company.",
    enabled: true,
    order: 3,
    status: "Running",
    lastRun: "2026-05-27T09:00:00",
  },
  {
    id: "ag_guess",
    name: "Email Guessing",
    description: "Generates likely email addresses from name + domain patterns.",
    enabled: true,
    order: 4,
    status: "Idle",
    lastRun: "2026-05-27T09:02:00",
  },
  {
    id: "ag_verify",
    name: "Email Verification",
    description: "Verifies guessed emails via Verifalia and stops once a deliverable address is found.",
    enabled: true,
    order: 5,
    status: "Idle",
    lastRun: "2026-05-27T09:03:00",
  },
  {
    id: "ag_outreach",
    name: "Outreach Generation",
    description: "Writes personalized subject + body using company research, role, and your product details.",
    enabled: true,
    order: 6,
    status: "Idle",
    lastRun: "2026-05-27T09:04:00",
  },
  {
    id: "ag_track",
    name: "Email Tracking & Follow-up",
    description: "Monitors the inbox every 15 minutes and sends contextual follow-ups until a meeting is booked.",
    enabled: true,
    order: 7,
    status: "Running",
    lastRun: "2026-05-27T09:10:00",
  },
  {
    id: "ag_meet",
    name: "Meeting Coordination",
    description: "Captures meeting links, stores details, and notifies both customer and contact.",
    enabled: true,
    order: 8,
    status: "Idle",
    lastRun: "2026-05-25T11:06:00",
  },
];

export const logs: LogEntry[] = [
  { id: "lg_1", at: "2026-05-27T09:12:00", category: "Email", message: "Reply detected from dana.whitfield@northwind.com (thread cv_1).", level: "info" },
  { id: "lg_2", at: "2026-05-27T09:10:00", category: "AI", message: "Follow-up generated for Brightwave Manufacturing.", level: "info" },
  { id: "lg_3", at: "2026-05-27T09:03:00", category: "Verification", message: "Verifalia: greg.hollis@summitretail.com → Unknown.", level: "warn" },
  { id: "lg_4", at: "2026-05-27T07:05:00", category: "AI", message: "Scoring agent ranked 480 companies for cmp_apex.", level: "info" },
  { id: "lg_5", at: "2026-05-27T07:00:00", category: "Campaign", message: "Enrichment started for 480 companies (cmp_apex).", level: "info" },
  { id: "lg_6", at: "2026-05-26T16:41:00", category: "Email", message: "Auto follow-up sent to tom@brightwave.io.", level: "info" },
  { id: "lg_7", at: "2026-05-26T15:02:00", category: "User", message: "Reviewer excluded Orbit Media Holdings from cmp_apex.", level: "info" },
  { id: "lg_8", at: "2026-05-24T08:30:00", category: "Verification", message: "Verification failed for 1 contact at Summit Retail Group.", level: "error" },
];

// ---- helpers ----
export const getCampaign = (id: string) => campaigns.find((c) => c.id === id);
export const companiesForCampaign = (id: string) =>
  companies.filter((c) => c.campaignId === id);
export const contactsForCompany = (id: string) =>
  contacts.filter((c) => c.companyId === id);
export const getCompany = (id: string) => companies.find((c) => c.id === id);

export const totals = {
  companiesUploaded: campaigns.reduce((s, c) => s + c.companiesUploaded, 0),
  companiesResearched: campaigns.reduce((s, c) => s + c.companiesResearched, 0),
  emailsSent: campaigns.reduce((s, c) => s + c.emailsSent, 0),
  repliesReceived: campaigns.reduce((s, c) => s + c.repliesReceived, 0),
  meetingsBooked: campaigns.reduce((s, c) => s + c.meetingsBooked, 0),
};

// Conversion funnel: Upload → Qualified → Contacted → Replied → Meeting
export const funnel = [
  { label: "Uploaded", value: 1140 },
  { label: "Qualified", value: 410 },
  { label: "Contacted", value: 360 },
  { label: "Replied", value: 125 },
  { label: "Meeting", value: 35 },
];
