"""add user access gating fields

Revision ID: 1b9cd2d2b2ee
Revises: f82b2984156b
Create Date: 2026-06-19 14:27:38.087485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b9cd2d2b2ee'
down_revision: Union[str, Sequence[str], None] = 'f82b2984156b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_status', sa.String(length=20), nullable=False, server_default='none'))
    op.add_column('users', sa.Column('access_note', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('access_review_note', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('access_requested_at', sa.DateTime(timezone=True), nullable=True))
    # Grandfather everyone who already exists so current users aren't locked out.
    op.execute("UPDATE users SET access_status = 'approved'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access_requested_at')
    op.drop_column('users', 'access_review_note')
    op.drop_column('users', 'access_note')
    op.drop_column('users', 'access_status')
    # ### end Alembic commands ###
